name: 'telegram_medical_pipeline'
version: '1.0.0'
config-version: 2

profile: 'telegram_medical_pipeline'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  telegram_medical_pipeline:
    staging:
      +materialized: view
    marts:
      +materialized: table
    intermediate:
      +materialized: view

vars:
  raw_schema: public
  staging_schema: staging
  marts_schema: marts 