version: 2

sources:
  - name: raw
    description: "Raw data from Telegram scraping"
    schema: raw
    tables:
      - name: telegram_messages
        description: "Raw Telegram messages from scraping"
        columns:
          - name: id
            description: "Primary key"
            tests:
              - unique
              - not_null
          - name: message_id
            description: "Unique Telegram message ID"
            tests:
              - unique
              - not_null
          - name: chat_id
            description: "Telegram chat ID"
          - name: chat_title
            description: "Chat title"
          - name: sender_id
            description: "Sender's Telegram ID"
          - name: sender_username
            description: "Sender's username"
          - name: sender_first_name
            description: "Sender's first name"
          - name: sender_last_name
            description: "Sender's last name"
          - name: message_text
            description: "Message content"
          - name: message_date
            description: "Message timestamp"
          - name: has_media
            description: "Whether message has media"
          - name: media_type
            description: "Type of media"
          - name: media_path
            description: "Path to media file"
          - name: reply_to_msg_id
            description: "ID of message being replied to"
          - name: forward_from
            description: "Forward source information"
          - name: scraped_at
            description: "When the message was scraped"
          - name: channel_name
            description: "Channel name"
            tests:
              - not_null
          - name: raw_data
            description: "Complete JSON data"
          - name: created_at
            description: "When the record was inserted" 